/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface VrmSecondaryanimationCollidergroup {
  /**
   * The node of the collider group for setting up collision detections.
   */
  node?: number;
  colliders?: {
    /**
     * The local coordinate from the node of the collider group.
     */
    offset?: {
      x?: number;
      y?: number;
      z?: number;
      [k: string]: any;
    };
    /**
     * The radius of the collider.
     */
    radius?: number;
    [k: string]: any;
  }[];
  [k: string]: any;
}
