/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Eye controller setting.
 */
export interface VrmFirstpersonDegreemap {
  /**
   * None linear mapping params. time, value, inTangent, outTangent
   */
  curve?: number[];
  /**
   * Look at input clamp range degree.
   */
  xRange?: number;
  /**
   * Look at map range degree from xRange.
   */
  yRange?: number;
  [k: string]: any;
}
