/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface VrmFirstperson {
  /**
   * The bone whose rendering should be turned off in first-person view. Usually Head is specified.
   */
  firstPersonBone?: number;
  /**
   * The target position of the VR headset in first-person view. It is assumed that an offset from the head bone to the VR headset is added.
   */
  firstPersonBoneOffset?: {
    x?: number;
    y?: number;
    z?: number;
    [k: string]: any;
  };
  /**
   * Switch display / undisplay for each mesh in first-person view or the others.
   */
  meshAnnotations?: VrmFirstpersonMeshannotation[];
  /**
   * Eye controller mode.
   */
  lookAtTypeName?: "Bone" | "BlendShape";
  lookAtHorizontalInner?: VrmFirstpersonDegreemap;
  lookAtHorizontalOuter?: VrmFirstpersonDegreemap;
  lookAtVerticalDown?: VrmFirstpersonDegreemap;
  lookAtVerticalUp?: VrmFirstpersonDegreemap;
  [k: string]: any;
}
export interface VrmFirstpersonMeshannotation {
  mesh?: number;
  firstPersonFlag?: string;
  [k: string]: any;
}
/**
 * Eye controller setting.
 */
export interface VrmFirstpersonDegreemap {
  /**
   * None linear mapping params. time, value, inTangent, outTangent
   */
  curve?: number[];
  /**
   * Look at input clamp range degree.
   */
  xRange?: number;
  /**
   * Look at map range degree from xRange.
   */
  yRange?: number;
  [k: string]: any;
}
