/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface VrmMaterial {
  name?: string;
  shader?: string;
  renderQueue?: number;
  floatProperties?: {
    [k: string]: any;
  };
  vectorProperties?: {
    [k: string]: any;
  };
  textureProperties?: {
    [k: string]: any;
  };
  keywordMap?: {
    [k: string]: any;
  };
  tagMap?: {
    [k: string]: any;
  };
  [k: string]: any;
}
