/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface VrmHumanoidBone {
  /**
   * Human bone name.
   */
  bone?:
    | "hips"
    | "leftUpperLeg"
    | "rightUpperLeg"
    | "leftLowerLeg"
    | "rightLowerLeg"
    | "leftFoot"
    | "rightFoot"
    | "spine"
    | "chest"
    | "neck"
    | "head"
    | "leftShoulder"
    | "rightShoulder"
    | "leftUpperArm"
    | "rightUpperArm"
    | "leftLowerArm"
    | "rightLowerArm"
    | "leftHand"
    | "rightHand"
    | "leftToes"
    | "rightToes"
    | "leftEye"
    | "rightEye"
    | "jaw"
    | "leftThumbProximal"
    | "leftThumbIntermediate"
    | "leftThumbDistal"
    | "leftIndexProximal"
    | "leftIndexIntermediate"
    | "leftIndexDistal"
    | "leftMiddleProximal"
    | "leftMiddleIntermediate"
    | "leftMiddleDistal"
    | "leftRingProximal"
    | "leftRingIntermediate"
    | "leftRingDistal"
    | "leftLittleProximal"
    | "leftLittleIntermediate"
    | "leftLittleDistal"
    | "rightThumbProximal"
    | "rightThumbIntermediate"
    | "rightThumbDistal"
    | "rightIndexProximal"
    | "rightIndexIntermediate"
    | "rightIndexDistal"
    | "rightMiddleProximal"
    | "rightMiddleIntermediate"
    | "rightMiddleDistal"
    | "rightRingProximal"
    | "rightRingIntermediate"
    | "rightRingDistal"
    | "rightLittleProximal"
    | "rightLittleIntermediate"
    | "rightLittleDistal"
    | "upperChest";
  /**
   * Reference node index
   */
  node?: number;
  /**
   * Unity's HumanLimit.useDefaultValues
   */
  useDefaultValues?: boolean;
  /**
   * Unity's HumanLimit.min
   */
  min?: {
    x?: number;
    y?: number;
    z?: number;
    [k: string]: any;
  };
  /**
   * Unity's HumanLimit.max
   */
  max?: {
    x?: number;
    y?: number;
    z?: number;
    [k: string]: any;
  };
  /**
   * Unity's HumanLimit.center
   */
  center?: {
    x?: number;
    y?: number;
    z?: number;
    [k: string]: any;
  };
  /**
   * Unity's HumanLimit.axisLength
   */
  axisLength?: number;
  [k: string]: any;
}
